image: "python:3.8"

before_script:
  - python --version
  - pip install flake8 mypy pytest

stages:
  - lint
  - tests

flake8:
  stage: lint
  script:
  - flake8 --ignore=F405,F403,E127,E501 *.py

mypy:
  stage: lint
  script:
    - mypy *.py

pytest:
  stage: tests
  script:
    - pytest