image: "python:3.8"

before_script:
  - python --version
  - pip install flake8 mypy pytest

stages:
  - lint
  - tests

flake8:
  stage: lint
  allow_failure: true
  script:
  - flake8 --ignore=F405,F403,E127,E501 src/

mypy:
  stage: lint
  allow_failure: true
  script:
    - mypy src/

pytest:
  stage: tests
  allow_failure: false
  script:
    - pytest